function plotBoots_MSW(FirstStageMC, n, coverageMCMSW, coverageMCBoots, horizons, columnnames, MCdraws, T, confidence, application, p, dataset_name, IRFselect, cumselect)
%  -Plots the MSW and Bootstrap MC coverage.
%  -Syntax:
%       plotBoots_MSW(FirstStageMC, n, coverageMCMSW, coverageMCBoots, horizons, columnnames, MCdraws, T, confidence, application, p, dataset_name, IRFselect, cumselect)
%  -Inputs:
%       FirstStageMC:      first stage for the Monte Carlo
%       n:                 dimension of the SVAR
%       coverageMCMSW:     Stores logical value 1 if the true IRF was covered by the Boostrap inference generated by each data for each
%                          draw. Stores logical value 0 otherwise
%       coverageMCBoots:   Stores logical value 1 if the true IRF was covered by the Bootstrap generated by each data for each draw.
%                          Stores logical value 0 otherwise
%       horizons:          Number of horizons for the Impulse Response Functions (IRFs) (does not include the impact or horizon 0)
%       columnnames:       Vector with the names for the endogenous variables, in the same order as ydata
%       MCdraws:           Number of draws for the Monte Carlo simulation
%       T:                 Size of the time series dataset
%       confidence:        Confidence level
%       application:       Name of the empirical application. This name will be used for creating and accessing folders.
%       p:                 Number of lags in the VAR model
%       dataset_name:      The name of the dataset used for generating the figures (used in the output label)
%       IRFselect:         Indices for the variables that the user wants separate IRF plots for 
%       cumselect:         Indices for the variables that the user wants cumulative IRF plots for

% This version: Semptember 18th, 2018
% Last edited by José Luis Montiel-Olea

%% 1) Plot coverage 


plots.order = 1:n;
           
graphcount  = 1;

figure(graphcount);

graphcount  = graphcount + 1;

impliedfirststage ...
            = round(mean(FirstStageMC),2);

addpath('functions/figuresfun');

%non-cumulative
for iplot = 1:n
    
    subplot(3,1,iplot)
    
    plot(0:horizons,mean(coverageMCBoots(iplot,:,:,1),3),'o'); hold on
    
    plot(0:horizons,mean(coverageMCMSW(iplot,:,:,1),3),'rx'); hold on
    
    axis([0 horizons .8 1]); 
    
    xlabel('Months after the shock');
    
    ylabel('MC Coverage');
    
    title(columnnames(iplot)); 
    
    if iplot == 2
        
        legend('Bootstrap AR',strcat('MSW C.I (',num2str(100*confidence),'%)'))
        
        legend('location','southeast')

    
    end

end

title_master = strcat('MC Coverage (',num2str(MCdraws),' MC draws, T=',num2str(T),', MC First Stage=',num2str(round(impliedfirststage,2)),')');

singletitle(title_master,'fontsize',16,'xoff',0,'yoff',.03);

%cumulative

figure(graphcount);

graphcount  = graphcount + 1;
 
for iplot   = 1:n
    
    subplot(3,1,iplot)
    
    plot(0:horizons,mean(coverageMCBoots(iplot,:,:,2),3),'o'); hold on
    
    plot(0:horizons,mean(coverageMCMSW(iplot,:,:,2),3),'rx'); hold on
    
    axis([0 horizons .8 1]); 
    
    xlabel('Months after the shock');
    
    ylabel('MC Coverage');
    
    title(columnnames(iplot)); 
    
    if iplot == 2
        
        legend('Bootstrap AR',strcat('MSW C.I (',num2str(100*confidence),'%)'))
        
        legend('location','southeast')
    
    end

end

title_master = strcat('Cumulative MC Coverage (',num2str(MCdraws),' MC draws, T=',num2str(T),', MC First Stage=',num2str(round(impliedfirststage,2)),')');

singletitle(title_master,'fontsize',16,'xoff',0,'yoff',.03);

%% 2) Save Coverage Plot

outdir = strcat('Output/',application,'/MC/Boots');

if exist(outdir,'dir')
    
    cd(outdir);
  
else
    
    mkdir(outdir);
    
    cd(outdir);

end

namdir = strcat(date,'_','K','_','p=',num2str(p),num2str(confidence));

if exist(namdir,'dir')
    
    cd(namdir);
  
else
    
    mkdir(namdir);
    
    cd(namdir);

end

output_label = strcat(dataset_name,'_p=',num2str(p),'_T=',num2str(T),'_confidence=',num2str(confidence),'.eps');

save_count   = 1;

figure(graphcount-1)

print(gcf,'-depsc2',strcat(num2str(save_count),'MC_Coverage_Cumulative_', output_label));

save_count   = save_count + 1;

figure(graphcount-2)

print(gcf,'-depsc2',strcat(num2str(save_count),'MC_Coverage_', output_label));

save_count   = save_count + 1;

save(strcat('MC_Coverage_',dataset_name,'_p=',num2str(p),'_T=',num2str(T),'_confidence=',num2str(confidence),'.mat'));

cd ..

cd ..

cd ..

cd ..

cd ..

%% 3) Plot Selected IRFs and Cumulatives

% This section of the script plots selected non-cumulative graphs for
% the selected IRF variables and selected cumulative graphs for the 
% selected cumselect variables. These plots are simply displayed, but
% not automatically saved. Section 17 generates the individual plots, which
% are saved.
if length(IRFselect) > 1
    
    figure(graphcount)

    graphcount  = graphcount + 1;

    plots.order = 1:length(IRFselect);

    for i = 1:length(IRFselect) 

        iplot   = IRFselect(i);

        if length(IRFselect) > ceil(sqrt(length(IRFselect))) * floor(sqrt(length(IRFselect)))

            subplot(ceil(sqrt(length(IRFselect))),ceil(sqrt(length(IRFselect))),plots.order(1,i));

        else

            subplot(ceil(sqrt(length(IRFselect))),floor(sqrt(length(IRFselect))),plots.order(1,i));

        end

        plot(0:horizons,mean(coverageMCBoots(iplot,:,:,1),3),'o'); hold on

        plot(0:horizons,mean(coverageMCMSW(iplot,:,:,1),3),'rx'); hold off

        axis([0 horizons .8 1]); 

        xlabel('Months after the shock');

        ylabel('MC Coverage');

        title(columnnames(iplot));

        if i == 1

            legend('Bootstrap AR',strcat('MSW C.I (',num2str(100*confidence),'%)'))

            legend('location','southeast')


        end

    end

    clear title_master;

    title_master = strcat('Selected MC Coverage (',num2str(MCdraws),' MC draws, T=',num2str(T),', MC First Stage=',num2str(round(impliedfirststage,2)),')');

    singletitle(title_master,'fontsize',16,'xoff',0,'yoff',.03);

end

%Cumulative plots

if length(cumselect) > 1
    
    figure(graphcount)

    graphcount  = graphcount + 1;

    plots.order = 1:length(cumselect);

    for i = 1:length(cumselect) 

        iplot   = cumselect(i);

        if length(IRFselect) > ceil(sqrt(length(IRFselect))) * floor(sqrt(length(IRFselect)))

            subplot(ceil(sqrt(length(IRFselect))),ceil(sqrt(length(IRFselect))),plots.order(1,i));

        else

            subplot(ceil(sqrt(length(IRFselect))),floor(sqrt(length(IRFselect))),plots.order(1,i));

        end

        plot(0:horizons,mean(coverageMCBoots(iplot,:,:,2),3),'o'); hold on

        plot(0:horizons,mean(coverageMCMSW(iplot,:,:,2),3),'rx'); hold off

        axis([0 horizons .8 1]); 

        xlabel('Months after the shock');

        ylabel('MC Coverage');

        title(columnnames(iplot));
        
        if i == 1

            legend('Bootstrap AR',strcat('MSW C.I (',num2str(100*confidence),'%)'))

            legend('location','southeast')


        end

    end

    title_master = strcat('Cumulative MC Coverage (',num2str(MCdraws),' MC draws, T=',num2str(T),', MC First Stage=',num2str(round(impliedfirststage,2)),')');

    singletitle(title_master,'fontsize',16,'xoff',0,'yoff',.03);
    
end


%% 4) Generating separate IRF (cumulative and non) plots

plots.order    = 1:length(IRFselect);

for i = 1:length(IRFselect) 

    iplot      = IRFselect(i);
    
    figure(graphcount);
    
    graphcount = graphcount + 1;
    
    plot(0:horizons,mean(coverageMCBoots(iplot,:,:,1),3),'o'); hold on
        
    plot(0:horizons,mean(coverageMCMSW(iplot,:,:,1),3),'rx'); hold off
    
    axis([0 horizons .8 1]);

    xlabel('Months after the shock');

    ylabel('MC Coverage');

    title(strcat(columnnames(iplot),num2str(MCdraws),'MC draws, T=',num2str(T),', MC First Stage=',num2str(round(impliedfirststage,2)),')'));

	legend('Bootstrap AR',strcat('MSW C.I (',num2str(100*confidence),'%)'))

    legend('location','southeast')

end

plots.order    = 1:length(cumselect);

for i = 1:length(cumselect) 

    iplot      = cumselect(i);
    
    figure(graphcount);
    
    graphcount = graphcount + 1;
    
    plot(0:horizons,mean(coverageMCBoots(iplot,:,:,2),3),'o'); hold on
    
    plot(0:horizons,mean(coverageMCMSW(iplot,:,:,2),3),'rx'); hold off

    axis([0 horizons .8 1]);

    xlabel('Months after the shock');

    ylabel('MC Coverage');

    title(strcat('Cumulative', {' '}, columnnames(iplot),num2str(MCdraws),'MC draws, T=',num2str(T),', MC First Stage=',num2str(round(impliedfirststage,2)),')'));

    legend('Bootstrap AR',strcat('MSW C.I (',num2str(100*confidence),'%)'))

	legend('location','southeast')

end

%% 21) Save separate selected IRF (cumulative and non) plots

outdir = strcat('Output/',application,'/MC/Boots');

if exist(outdir,'dir')
    
    cd(outdir);
  
else
    
    mkdir(outdir);
    
    cd(outdir);

end

output_label = strcat(dataset_name,'_p=',num2str(p),'_T=',num2str(T),'_confidence=',num2str(confidence),'.eps');

namdir       = strcat(date,'_','K','_','p=',num2str(p),num2str(confidence));

if exist(namdir,'dir')
    
    cd(namdir);
  
else
    
    mkdir(namdir);
    
    cd(namdir);

end

for i = 1:(length(cumselect)) 
    
    figure(graphcount - i)
    
    print(gcf,'-depsc2',strcat(num2str(save_count),'MC_Coverage_Separate_Cumulative_', output_label));
    
    save_count = save_count + 1;

end

for i = length(cumselect)+1:(length(IRFselect)+length(cumselect))
    
    figure(graphcount - i)

    print(gcf,'-depsc2',strcat(num2str(save_count),'MC_Coverage_Separate_', output_label, num2str(graphcount-i)));
    
    save_count = save_count + 1;
    
end

cd ..
    
cd ..

cd ..

cd ..

cd ..
